name: Sprawdzanie dostępności

on:
  schedule:
    - cron: "*/15 7-22 * * *"  # co 15 minut w godz. 7:00–22:45 UTC
  workflow_dispatch:

jobs:
  check_product:
    runs-on: ubuntu-latest
    steps:
      - name: Klon repo
        uses: actions/checkout@v3

      - name: Instalacja bibliotek
        run: pip install beautifulsoup4 requests

      - name: Start
        run: python check_product.py
